# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='firstname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^.*?[(!"#\\$%\\(\\)\\*\\+\\/\\\\:;<=>\\?@\\[\\]\\^_`\\{\\|\\}~)]+.*?$', 'Special characters are forbidden', 'invalid', inverse_match=True)]),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='lastname',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^.*?[(!"#\\$%\\(\\)\\*\\+\\/\\\\:;<=>\\?@\\[\\]\\^_`\\{\\|\\}~)]+.*?$', 'Special characters are forbidden', 'invalid', inverse_match=True)]),
        ),
    ]
