# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 02:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_auto_20160731_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='holder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bank_accounts.BankUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(default='DE1212345678012345678', max_length=34),
            preserve_default=False,
        ),
    ]
