# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 03:07
from __future__ import unicode_literals

import bank_accounts.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_auto_20160731_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='bank_accounts.BankUser'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(max_length=34, validators=[bank_accounts.models.NoSpecialCharacters(), django.core.validators.RegexValidator('^[A-Z]{2}\\d\\d([A-Z]|\\d){1,30}$', 'Not a valid IBAN-format.', 'invalid')]),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='firstname',
            field=models.CharField(max_length=255, validators=[bank_accounts.models.NoSpecialCharacters()]),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='lastname',
            field=models.CharField(max_length=255, validators=[bank_accounts.models.NoSpecialCharacters()]),
        ),
    ]
